pub const TOKEN_VAR: &str = "DISCORD_TOKEN";
pub const APPLICATION_ID_VAR: &str = "APPLICATION_ID";
pub const WEBHOOK_VAR: &str = "ASYNC_WEBHOOK_URL";
pub const FOXLISK_USER_ID: u64 = 255676979460702210;
