name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: cargo --version
    - run: rustc --version
    - name: Build
      run: cargo build --verbose --features "testing"
    - name: Run tests
      run: cargo test --verbose --features "testing"
